[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
securitytxt = "5HZ5C2TDCv7Wy4Uxqy4C8QMJ21kK1ZVkrALUyZzmGezs"
[programs.devnet]
securitytxt = "5HZ5C2TDCv7Wy4Uxqy4C8QMJ21kK1ZVkrALUyZzmGezs"
[programs.mainnet]
securitytxt = "798shHqbnsSvY6odSdQJXaV2UEf1pmcBE7jsWyBV7Pc4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/default/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
