[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
securitytxt = "5HZ5C2TDCv7Wy4Uxqy4C8QMJ21kK1ZVkrALUyZzmGezs"
[programs.devnet]
securitytxt = "5HZ5C2TDCv7Wy4Uxqy4C8QMJ21kK1ZVkrALUyZzmGezs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/solana/wallet/chat/info.txt"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
